window_title = 'YAARX'
window_logo = './logo.jpg'
binary_file = './bin' # for compiled yaarx binary file

choice_list = 'default'
# adjust the order of options in the program selection combobox
# must be a list[] or 'default'
# 'default' means the same order for programs in the config file.

word_size_list = [4, 8, 16, 32]
input_types = ['hex', 'decimal', 'binary']

default_parameter_type = 0
# the actual input type allowed for the binary file. It can be specified for a particular parameter with modifing
# the key named 'type' in this parameter. 0 for hexdecimal, 1 for decimal and 2 for binary.

default_output_lines = [-2]
# a list of lines which need to be formated and display as the output of the program. -2 indicate the second last line.

# a templete for programes

# [programs.demo-program]
#     name = 'demo-program' # must be the same name as the binary file
#     description = 'a templete for a demo program' # will be display as instructions
#     output_lines = [2,3,4] # a list of lines which need to be formated and display as the output of the program.
#     except_word_size = [4] # a list of word size that may cause error for this program

#     [[programs.demo-program.param]] # list of parameters
#         name = 'a' # will be display as the lable of the parameter
#         type = 0 # type of the value allowed

#     [[programs.demo-program.param]]
#         name = 'b'
#         type = 0

[programs.xdp-add]
    name = 'xdp-add'
    description = 'The XOR differential probability (XDP) of modular addition.'

    [[programs.xdp-add.param]]
        name = 'da'

    [[programs.xdp-add.param]]
        name = 'db'

    [[programs.xdp-add.param]]
        name = 'dc'


[programs.max-xdp-add]
    name = 'max-xdp-add'
    description = 'The maximum XOR differential probability of modular addition.'

    [[programs.max-xdp-add.param]]
        name = 'da'

    [[programs.max-xdp-add.param]]
        name = 'db'

[programs.adp-xor]
    name = 'adp-xor'
    description = 'The modular addition differential probability (ADP) of XOR.'

    [[programs.adp-xor.param]]
        name = 'da'

    [[programs.adp-xor.param]]
        name = 'db'

    [[programs.adp-xor.param]]
        name = 'dc'


[programs.max-adp-xor]
    name = 'max-xdp-add'
    description = 'The maximum modular addition differential probability of XOR.'

    [[programs.max-adp-xor.param]]
        name = 'da'

    [[programs.max-adp-xor.param]]
        name = 'db'

[programs.adp-lsh]
    name = 'adp-lsh'
    description = 'The modular addition differential probability of left shift (LSH).'

    [[programs.adp-lsh.param]]
        name = 'r'
        type = 1

    [[programs.adp-lsh.param]]
        name = 'da'

    [[programs.adp-lsh.param]]
        name = 'db'


[programs.adp-rsh]
    name = 'adp-rsh'
    description = 'The modular addition differential probability of right shift (RSH).'
    output_lines = [2,3,4,5]

    [[programs.adp-rsh.param]]
        name = 'r'
        type = 1

    [[programs.adp-rsh.param]]
        name = 'da'

    [[programs.adp-rsh.param]]
        name = 'db'


[programs.adp-xor-fi]
    name = 'adp-xor-fi'
    description = 'The modular addition differential probability of XOR with one fixed input.'

    [[programs.adp-xor-fi.param]]
        name = 'a'

    [[programs.adp-xor-fi.param]]
        name = 'db'

    [[programs.adp-xor-fi.param]]
        name = 'dc'

[programs.max-adp-xor-fi]
    name = 'max-adp-xor-fi'
    description = 'The maximum modular addition differential probability of XOR with one fixed input.'

    [[programs.max-adp-xor-fi.param]]
        name = 'a'

    [[programs.max-adp-xor-fi.param]]
        name = 'db'

[programs.adp-xor3]
    name = 'adp-xor3'
    description = 'The modular addition differential probability of XOR with three inputs.'

    [[programs.adp-xor3.param]]
        name = 'da'

    [[programs.adp-xor3.param]]
        name = 'db'

    [[programs.adp-xor3.param]]
        name = 'dc'

    [[programs.adp-xor3.param]]
        name = 'dd'

[programs.max-adp-xor3]
    name = 'max-adp-xor3'
    description = 'The maximum modular addition differential probability of XOR with three inputs:'
    [[programs.max-adp-xor3.param]]
        name = 'da'

    [[programs.max-adp-xor3.param]]
        name = 'db'

    [[programs.max-adp-xor3.param]]
        name = 'dc'

[programs.eadp-tea-f]
    name = 'eadp-tea-f'
    description = 'The expected additive DP (EADP) of the F-function of TEA, averaged over all round keys and constants.'
    except_word_size = [4]

    [[programs.eadp-tea-f.param]]
        name = 'dx'

    [[programs.eadp-tea-f.param]]
        name = 'dy'

[programs.max-eadp-tea-f]
    name = 'max-eadp-tea-f'
    description = 'The maximum expected additive DP (EADP) of the F-function of TEA, averaged over all round keys and constants.'
    except_word_size = [4]

    [[programs.max-eadp-tea-f.param]]
        name = 'dx'

